[2024-01-23T15:59:43.902+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python_files_dag.execute_python_file_load manual__2024-01-23T15:59:18.851991+00:00 [queued]>
[2024-01-23T15:59:43.915+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python_files_dag.execute_python_file_load manual__2024-01-23T15:59:18.851991+00:00 [queued]>
[2024-01-23T15:59:43.916+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-23T15:59:44.074+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): execute_python_file_load> on 2024-01-23 15:59:18.851991+00:00
[2024-01-23T15:59:44.077+0000] {standard_task_runner.py:60} INFO - Started process 391 to run task
[2024-01-23T15:59:44.079+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python_files_dag', 'execute_python_file_load', 'manual__2024-01-23T15:59:18.851991+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgtfa08w8']
[2024-01-23T15:59:44.081+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask execute_python_file_load
[2024-01-23T15:59:44.384+0000] {task_command.py:423} INFO - Running <TaskInstance: execute_python_files_dag.execute_python_file_load manual__2024-01-23T15:59:18.851991+00:00 [running]> on host b977193ffa62
[2024-01-23T15:59:44.712+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python_files_dag' AIRFLOW_CTX_TASK_ID='execute_python_file_load' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T15:59:18.851991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-23T15:59:18.851991+00:00'
[2024-01-23T15:59:44.715+0000] {logging_mixin.py:188} INFO - Error executing file C:\Users\havet\Desktop\workflow_1\load.py: [Errno 2] No such file or directory: 'C:\\Users\\havet\\Desktop\\workflow_1\\load.py'
[2024-01-23T15:59:44.715+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T15:59:44.729+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=execute_python_files_dag, task_id=execute_python_file_load, execution_date=20240123T155918, start_date=20240123T155943, end_date=20240123T155944
[2024-01-23T15:59:44.856+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T15:59:44.875+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
